title: "О книге"
author: "Назаров Руслан"
copyright: "2026"

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - html_image

# Настройки оформления
html:
  home_page_in_toc: true
  logo: "logo.png"
  favicon: "logo.png"
  analytics:
    google_analytics_id: "G-L9BCXQ2FD1"
  extra_css:
    - _static/custom.css
  navbar_brand_box_2:          # В некоторых версиях помогает этот блок
    logo_only: false

metadata:
  description: "Изучение иностранных языков с помощью диалектики"
  keywords: "Языки, диалектика, лингвистика, Руслан Назаров"
  image_path: "logo.png"

# Настройки автора и копирайта
author: "Назаров Руслан"
copyright: "2026"  # Или "2022–2026", если проект длительный

sphinx:
  config:
    html_theme_options:
      logo_only: false         # ВАЖНО: здесь тоже должно быть false












