title: "О книге"
author: "Назаров Руслан"
copyright: "2026"

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - html_image

# Настройки оформления
html:
  home_page_in_toc: true
  logo: "logo.png"
  favicon: "logo.png"
  extra_css:
    - _static/custom.css
  navbar_brand_box_2:          # В некоторых версиях помогает этот блок
    logo_only: false
  html:
  extra_footer: |
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-J21RBQ48WS"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-PLQBBT7CFS');
    </script>

metadata:
  description: "Изучение иностранных языков с помощью диалектики"
  keywords: "Языки, диалектика, лингвистика, Руслан Назаров"
  image_path: "logo.png"

# Настройки автора и копирайта
author: "Назаров Руслан"
copyright: "2026"  # Или "2022–2026", если проект длительный

sphinx:
  config:
    html_theme_options:
      logo_only: false         # ВАЖНО: здесь тоже должно быть false


















