name: deploy-book

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install jupyter-book
<<<<<<< HEAD
        run: pip install "jupyter-book==0.15.1"
=======
        run: pip install "jupyter-book==0.15.1" sphinx-sitemap
>>>>>>> 7b1707ac79d4b28dc614e5a547d1c6f6bf16dbf9

      - name: Build the book
        run: |
          jupyter-book build .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_build/html

      - name: Deploy to GitHub Pages
        id: deployment
<<<<<<< HEAD
        uses: actions/deploy-pages@v4
=======
        uses: actions/deploy-pages@v4
>>>>>>> 7b1707ac79d4b28dc614e5a547d1c6f6bf16dbf9
